/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    apps: App;
    countries: Country;
    "user-requests": UserRequest;
    "hazards-index": HazardsIndex;
    "english-levels": EnglishLevel;
    "lgbtq-levels": LgbtqLevel;
    plugTypes: PlugType;
    media: Media;
    erasmusfundings: Erasmusfunding;
    "payload-kv": PayloadKv;
    users: User;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    apps: AppsSelect<false> | AppsSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    "user-requests": UserRequestsSelect<false> | UserRequestsSelect<true>;
    "hazards-index": HazardsIndexSelect<false> | HazardsIndexSelect<true>;
    "english-levels": EnglishLevelsSelect<false> | EnglishLevelsSelect<true>;
    "lgbtq-levels": LgbtqLevelsSelect<false> | LgbtqLevelsSelect<true>;
    plugTypes: PlugTypesSelect<false> | PlugTypesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    erasmusfundings: ErasmusfundingsSelect<false> | ErasmusfundingsSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ("false" | "none" | "null")
    | false
    | null
    | ("en" | "de")
    | ("en" | "de")[];
  globals: {};
  globalsSelect: {};
  locale: "en" | "de";
  user: User & {
    collection: "users";
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apps".
 */
export interface App {
  id: string;
  name: string;
  description?: string | null;
  url_android?: string | null;
  url_ios?: string | null;
  image?: (string | null) | Media;
  isMostPopular?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: string;
  name: string;
  slug?: string | null;
  hiddenGem?: boolean | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  culturalAndSocialNorms?: {
    description?: string | null;
    vegetarianPopulationShare?: number | null;
    veganPopulationShare?: number | null;
    lgbtqFriendliness?: (string | null) | LgbtqLevel;
    lgbtqFriendlinessScore?: number | null;
    avgCostOfLiving?: number | null;
    erasmusFunding?: (string | null) | Erasmusfunding;
    culturalTips?:
      | {
          tip: {
            title: string;
            description: string;
            link?:
              | {
                  title: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  languageAndCommunication?: {
    description?: string | null;
    localLanguages?:
      | {
          language: string;
          id?: string | null;
        }[]
      | null;
    englishLevels?: (string | null) | EnglishLevel;
    englishLevelScore?: number | null;
    messengerApps?: (string | App)[] | null;
    languageTips?:
      | {
          tip: {
            title: string;
            description: string;
            link?:
              | {
                  title: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  navTransport?: {
    desc?: string | null;
    transportApps?: (string | App)[] | null;
    driverPermits?: {
      idpOk?: boolean | null;
      euOk?: boolean | null;
      iadpOk?: boolean | null;
      aseanOk?: boolean | null;
    };
    driverPermitType?: ("internationalDp" | "euDp" | "iaDp" | "aseanDp") | null;
    navApps?: (string | App)[] | null;
    transportTips?:
      | {
          tip: {
            title: string;
            description: string;
            link?:
              | {
                  title: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  moneyAndPayments?: {
    description?: string | null;
    acceptedCurrencies?:
      | {
          currency: string;
          "currency symbol"?: string | null;
          id?: string | null;
        }[]
      | null;
    paymentMethods?: {
      "Payment by Card (%)"?: number | null;
      "Payment by Cash (%)"?: number | null;
      "Payment by App (%)"?: number | null;
    };
    paymentApps?: (string | App)[] | null;
    onlineShoppingApps?: (string | App)[] | null;
    moneyTips?:
      | {
          tip: {
            title: string;
            description: string;
            link?:
              | {
                  title: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  safetyAndLegal?: {
    description?: string | null;
    visaRequired?: string | null;
    emergencyNumbers?: {
      police?: string | null;
      ambulance?: string | null;
      fire?: string | null;
    };
    naturalHazardsIndexEnum?: (string | null) | HazardsIndex;
    naturalHazardsIndexValue?: number | null;
    safetyTips?:
      | {
          tip: {
            title: string;
            description: string;
            link?:
              | {
                  title: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  dailyLifeAndLifestyle?: {
    description?: string | null;
    findingFlatResources?:
      | {
          "Platform name"?: string | null;
          platform?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    electricalPlugTypes?:
      | {
          plugType: string | PlugType;
          voltage?: string | null;
          id?: string | null;
        }[]
      | null;
    foodDeliveryApps?: (string | App)[] | null;
    socialMediaApps?: (string | App)[] | null;
    datingApps?: (string | App)[] | null;
    openingDays?: ("0" | "1" | "2" | "3" | "4" | "5" | "6")[] | null;
    dailyTips?:
      | {
          tip: {
            title: string;
            description: string;
            link?:
              | {
                  title: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  health?: {
    description?: string | null;
    healthInsurance?: {
      isRequired?: boolean | null;
      description?: string | null;
    };
    vaccinations?: {
      requiredVaccinations?:
        | {
            name: string;
            notes?: string | null;
            id?: string | null;
          }[]
        | null;
      riskBasedVaccinations?:
        | {
            name: string;
            notes?: string | null;
            id?: string | null;
          }[]
        | null;
      generalVaccinations?:
        | {
            name: string;
            notes?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    mentalHealthHelp?: {
      name?: string | null;
      phone?: string | null;
      website?: string | null;
    };
    antiDiscriminationHelp?: {
      name?: string | null;
      phone?: string | null;
      website?: string | null;
    };
    sexualHarassmentHelp?: {
      name?: string | null;
      phone?: string | null;
      website?: string | null;
    };
    healthTips?:
      | {
          tip: {
            title: string;
            description: string;
            link?:
              | {
                  title: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lgbtq-levels".
 */
export interface LgbtqLevel {
  id: string;
  name: string;
  range?: string | null;
  description?: string | null;
  icon?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "erasmusfundings".
 */
export interface Erasmusfunding {
  id: string;
  groupName: string;
  description?: string | null;
  monthlyFunding: {
    min: number;
    max: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "english-levels".
 */
export interface EnglishLevel {
  id: string;
  name: string;
  description?: string | null;
  icon?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hazards-index".
 */
export interface HazardsIndex {
  id: string;
  name: string;
  description?: string | null;
  icon?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugTypes".
 */
export interface PlugType {
  id: string;
  code: string;
  image: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-requests".
 */
export interface UserRequest {
  id: string;
  title?: string | null;
  countryExperience?: {
    hasVisited?: ("yes" | "no") | null;
    durationOfStay?: string | null;
  };
  issue?: {
    issueType?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: "apps";
        value: string | App;
      } | null)
    | ({
        relationTo: "countries";
        value: string | Country;
      } | null)
    | ({
        relationTo: "user-requests";
        value: string | UserRequest;
      } | null)
    | ({
        relationTo: "hazards-index";
        value: string | HazardsIndex;
      } | null)
    | ({
        relationTo: "english-levels";
        value: string | EnglishLevel;
      } | null)
    | ({
        relationTo: "lgbtq-levels";
        value: string | LgbtqLevel;
      } | null)
    | ({
        relationTo: "plugTypes";
        value: string | PlugType;
      } | null)
    | ({
        relationTo: "media";
        value: string | Media;
      } | null)
    | ({
        relationTo: "erasmusfundings";
        value: string | Erasmusfunding;
      } | null)
    | ({
        relationTo: "users";
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apps_select".
 */
export interface AppsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  url_android?: T;
  url_ios?: T;
  image?: T;
  isMostPopular?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  hiddenGem?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  culturalAndSocialNorms?:
    | T
    | {
        description?: T;
        vegetarianPopulationShare?: T;
        veganPopulationShare?: T;
        lgbtqFriendliness?: T;
        lgbtqFriendlinessScore?: T;
        avgCostOfLiving?: T;
        erasmusFunding?: T;
        culturalTips?:
          | T
          | {
              tip?:
                | T
                | {
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  languageAndCommunication?:
    | T
    | {
        description?: T;
        localLanguages?:
          | T
          | {
              language?: T;
              id?: T;
            };
        englishLevels?: T;
        englishLevelScore?: T;
        messengerApps?: T;
        languageTips?:
          | T
          | {
              tip?:
                | T
                | {
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  navTransport?:
    | T
    | {
        desc?: T;
        transportApps?: T;
        driverPermits?:
          | T
          | {
              idpOk?: T;
              euOk?: T;
              iadpOk?: T;
              aseanOk?: T;
            };
        driverPermitType?: T;
        navApps?: T;
        transportTips?:
          | T
          | {
              tip?:
                | T
                | {
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  moneyAndPayments?:
    | T
    | {
        description?: T;
        acceptedCurrencies?:
          | T
          | {
              currency?: T;
              "currency symbol"?: T;
              id?: T;
            };
        paymentMethods?:
          | T
          | {
              "Payment by Card (%)"?: T;
              "Payment by Cash (%)"?: T;
              "Payment by App (%)"?: T;
            };
        paymentApps?: T;
        onlineShoppingApps?: T;
        moneyTips?:
          | T
          | {
              tip?:
                | T
                | {
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  safetyAndLegal?:
    | T
    | {
        description?: T;
        visaRequired?: T;
        emergencyNumbers?:
          | T
          | {
              police?: T;
              ambulance?: T;
              fire?: T;
            };
        naturalHazardsIndexEnum?: T;
        naturalHazardsIndexValue?: T;
        safetyTips?:
          | T
          | {
              tip?:
                | T
                | {
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  dailyLifeAndLifestyle?:
    | T
    | {
        description?: T;
        findingFlatResources?:
          | T
          | {
              "Platform name"?: T;
              platform?: T;
              description?: T;
              id?: T;
            };
        electricalPlugTypes?:
          | T
          | {
              plugType?: T;
              voltage?: T;
              id?: T;
            };
        foodDeliveryApps?: T;
        socialMediaApps?: T;
        datingApps?: T;
        openingDays?: T;
        dailyTips?:
          | T
          | {
              tip?:
                | T
                | {
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  health?:
    | T
    | {
        description?: T;
        healthInsurance?:
          | T
          | {
              isRequired?: T;
              description?: T;
            };
        vaccinations?:
          | T
          | {
              requiredVaccinations?:
                | T
                | {
                    name?: T;
                    notes?: T;
                    id?: T;
                  };
              riskBasedVaccinations?:
                | T
                | {
                    name?: T;
                    notes?: T;
                    id?: T;
                  };
              generalVaccinations?:
                | T
                | {
                    name?: T;
                    notes?: T;
                    id?: T;
                  };
            };
        mentalHealthHelp?:
          | T
          | {
              name?: T;
              phone?: T;
              website?: T;
            };
        antiDiscriminationHelp?:
          | T
          | {
              name?: T;
              phone?: T;
              website?: T;
            };
        sexualHarassmentHelp?:
          | T
          | {
              name?: T;
              phone?: T;
              website?: T;
            };
        healthTips?:
          | T
          | {
              tip?:
                | T
                | {
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-requests_select".
 */
export interface UserRequestsSelect<T extends boolean = true> {
  title?: T;
  countryExperience?:
    | T
    | {
        hasVisited?: T;
        durationOfStay?: T;
      };
  issue?:
    | T
    | {
        issueType?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hazards-index_select".
 */
export interface HazardsIndexSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "english-levels_select".
 */
export interface EnglishLevelsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lgbtq-levels_select".
 */
export interface LgbtqLevelsSelect<T extends boolean = true> {
  name?: T;
  range?: T;
  description?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugTypes_select".
 */
export interface PlugTypesSelect<T extends boolean = true> {
  code?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "erasmusfundings_select".
 */
export interface ErasmusfundingsSelect<T extends boolean = true> {
  groupName?: T;
  description?: T;
  monthlyFunding?:
    | T
    | {
        min?: T;
        max?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
